VERSION 0.6

FROM golang:1.20
WORKDIR /acme-example

deps:
  COPY go.mod go.sum ./

  COPY --dir ../../../baseplate-go+artifact-config/config ../../
  COPY --dir ../../../baseplate-go+artifact-http/http ../../

  RUN go mod download
  # Output these back in case go mod download changes them.
  SAVE ARTIFACT go.mod AS LOCAL go.mod
  SAVE ARTIFACT go.sum AS LOCAL go.sum

build:
  FROM +deps
  COPY *.go .
  RUN CGO_ENABLED=0 go build -trimpath -ldflags='-s -w -extldflags "-static"' -o bin/acme-example github.com/bloominlabs/hostin-proj/acme-example
  SAVE ARTIFACT bin/acme-example /acme-example AS LOCAL bin/acme-example

docker:
  FROM gcr.io/distroless/base-debian11:debug-nonroot
  COPY +build/acme-example /usr/bin/acme-example
  ENTRYPOINT ["/usr/bin/acme-example"]
  SAVE IMAGE --push ghcr.io/bloominlabs/acme-example:latest
