# https://github.com/hashicorp/vault/pull/12358
VERSION 0.6
FROM golang:1.20
WORKDIR /loadchecker

deps:
  COPY go.mod go.sum ./

  COPY --dir ../../../baseplate-go+artifact-config/config ../../
  COPY --dir ../../../baseplate-go+artifact-http/http ../../

  RUN go mod download
  # Output these back in case go mod download changes them.
  SAVE ARTIFACT go.mod AS LOCAL go.mod
  SAVE ARTIFACT go.sum AS LOCAL go.sum

build:
  FROM +deps
  COPY main.go .
  RUN GO111MODULE=on CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -extldflags '-static'" -trimpath -o bin/loadchecker github.com/bloominlabs/hostin-proj/loadchecker
  SAVE ARTIFACT bin/loadchecker /loadchecker AS LOCAL bin/loadchecker

test:
  FROM +deps
  COPY ./mock ./mock
  COPY main.go .
  COPY main_test.go .
  RUN go test

docker:
  FROM gcr.io/distroless/base-debian11:debug-nonroot
  COPY +build/loadchecker /usr/bin
  ENTRYPOINT ["/usr/bin/loadchecker"]
  SAVE IMAGE loadchecker:latest
  SAVE IMAGE --push ghcr.io/bloominlabs/loadchecker:latest
