# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build-and-test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples: ["acme-example", "http-server", "srv-client"]
    steps:
      - uses: actions/checkout@v4
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: earthly --ci +build 
        working-directory: "./example/${{ matrix.examples }}"

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gen dependabot
        run: |
          ./scripts/dependabot.sh
          git diff -s --exit-code || (echo 'ALL_MODULES have been changed, please run "./scripts/dependabot.sh" and commit the changes in this PR.' && exit 1)
