# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples: ["acme-example", "http-server", "srv-client"]
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1.0.2
      - run: earthly --ci +build 
        working-directory: "./example/${{ matrix.examples }}"
